// src/pages/index.tsx
import Head from 'next/head';
import styled from 'styled-components';
import PageWrapper from '../components/PageWrapper';
import { device } from '../constants/device';
import glitch from '../styles/glitch.module.scss';

export const Main = styled.main`
  flex-grow: 1;
  justify-content: center;
  align-items: center;
  display: flex;
`;

const StyledGlitch = styled.h1`
  font-size: 3rem;
  font-family: 'Playball', cursive;

  @media ${device.tablet} {
    font-size: 5rem;
  }
`;

export default function TopPage() {
  return (
    <PageWrapper>
      <Head>
        <title>0x000000</title>
      </Head>

      <Main>
        <StyledGlitch data-text="0x000000" className={glitch.glitch}>
          0x000000
        </StyledGlitch>
      </Main>
    </PageWrapper>
  );
}

// pages/index.vue
<template>
  <b-container class="main">
    <h1 class="glitch title" data-text="0x000000">0x000000</h1>
  </b-container>
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({})
</script>

<style lang="scss" scoped>
.main {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

.title {
  font-size: 6rem;

  @media (max-width: 576px) {
    font-size: 3rem;
  }
}
</style>
